name: Deploy to Cloudways

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        chmod 600 /home/runner/.ssh/id_rsa
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Sync files
      run: rsync -avz -vvv --exclude '.git*' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/master/applications/yebcquwpvc/public_html
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}